USE toj_sitoweb;
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (1, 38, 325, 'M', 'Cappotti da uomo Tasca Colore unico Ufficio', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (2, 38, 325, 'M', 'Cappotti da uomo Tasca Colore unico Ufficio', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (3, 41, 325, 'M', 'Cappotto a quadri con bottone da uomo', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (4, 30, 325, 'M', 'Cappotto a quadri con bottone e collo a V dentellato', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (5, 27, 325, 'M', 'Cappotto a quadri con doppia tasca', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (6, 44, 325, 'M', 'Cappotto con cappuccio con doppio petto da uomo', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (7, 37, 325, 'M', 'Cappotto con monopetto e tasca laterale', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (8, 71, 325, 'M', 'Cappotto con tasca e pulsante clacson', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (9, 35, 325, 'M', 'Cappotto da uomo con cappuccio e tasca frontale con patta', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (10, 37, 325, 'M', 'Cappotto da uomo con dettaglio di patta', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (11, 71, 325, 'M', 'Cappotto da uomo con doppia tasca monopetto', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (12, 36, 325, 'M', 'Cappotto monopetto da uomo con colletto dentellato grigio', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (13, 26, 325, 'M', 'Cappotto teddy con doppio petto', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (14, 41, 325, 'M', 'Cappotto da uomo con spalle scoperte', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (15, 34, 325, 'M', 'Cappotto da uomo in pile color block con patch a lettere con cerniera', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (16, 40, 325, 'M', 'Cappotto da uomo in pile con motivo a quadri e tasca con patta', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (17, 37, 325, 'M', 'Cappotto da uomo in tinta unita con revers', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (18, 83, 325, 'M', 'Cappotto da uomo in tinta unita con risvolto abbottonato', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (19, 36, 325, 'M', 'Cappotto da uomo in tinta unita con risvolto abbottonato', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (20, 36, 325, 'M', 'Overcoat con bottone e patta da uomo', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (21, 73, 325, 'M', 'Soprabito anteriore con tasca scozzese da uomo', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (22, 27, 325, 'M', 'Cappotto monopetto da uomo con colletto dentellato grigio', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (23, 28, 325, 'M', 'Bomber da uomo con fodera in pile semplice', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (24, 31, 325, 'M', 'Bomber da uomo con tasca obliqua e zip', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (25, 38, 325, 'M', 'Bomber trapuntato da uomo con zip', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (26, 38, 325, 'M', 'Bomber trapuntato da uomo con zip', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (27, 17, 325, 'M', 'Giacca da uomo Cerniera Blocchi di colore Bianco e Nero College', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (28, 27, 325, 'M', 'Giacca da uomo Cerniera Colore unico Verde militare College', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (29, 24, 325, 'M', 'Giacca da uomo Cordone Colore unico Grigio', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (30, 28, 325, 'M', 'Giacca a vento con cappuccio e zip mimetico', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (31, 29, 325, 'M', 'Giacca a vento con tasca e patta gialla', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (32, 34, 325, 'M', 'Giacca a vento con zip color block', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (33, 43, 325, 'M', 'Giacca a vento da uomo con bottoni', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (34, 21, 325, 'M', 'Giacca bomber con grafica di lettere senza maglietta', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (35, 22, 325, 'M', 'Giacca bomber con ricamo lettera', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (36, 22, 325, 'M', 'Giacca bomber con ricamo lettera', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (37, 22, 325, 'M', 'Giacca bomber con ricamo lettera', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (38, 22, 325, 'M', 'Giacca bomber con stampa mimetica', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (39, 21, 325, 'M', 'Giacca bomber con zip', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (40, 24, 325, 'M', 'Giacca con cappuccio e coulisse con zip color black', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (41, 43, 325, 'M', 'Giacca da ciclisimo con collo a bavero in PU', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (42, 59, 325, 'M', 'Giacca da moto in pelle PU con cerniera frontale da uomo', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (43, 28, 325, 'M', 'Giacca da uomo con cappuccio e zip con coulisse', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (44, 28, 325, 'M', 'Giacca da uomo con cappuccio e zip con coulisse', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (45, 37, 325, 'M', 'Giacca da uomo in cotone con cappuccio, tasca laterale con cerniera e dettaglio in fettuccia', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (46, 24, 325, 'M', 'Giacca mimetica con zip', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (47, 44, 325, 'M', 'Giacca piumino con toppa', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (48, 9, 325, 'M', 'Costume da bagno con coulisse con stampa tropicale', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (49, 15, 325, 'M', 'Costume da bagno con coulisse con tasca con zip', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (50, 15, 325, 'M', 'Costume da bagno con coulisse con tasca con zip', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (51, 15, 325, 'M', 'Costume da bagno con coulisse con tasca con zip', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (52, 15, 325, 'M', 'Costume da bagno con coulisse con tasca con zip', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (53, 12, 325, 'M', 'Costume da bagno con coulisse in vita grafica con lettera blu', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (54, 12, 325, 'M', 'Costume da bagno con coulisse in vita grafica con lettera', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (55, 12, 325, 'M', 'Costume da bagno con coulisse in vita grafica con lettera', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (56, 9, 325, 'M', 'Costume da bagno da uomo con coulisse e stampa albero di palma', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (57, 14, 325, 'M', 'Costume da bagno da uomo con stampa fenicottero', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (58, 14, 325, 'M', 'Costume da bagno da uomo con stampa fenicottero', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (59, 8, 325, 'M', 'Costumi da uomo Animale Vacanza', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (60, 14, 325, 'M', 'Costumi da uomo Cordone Fenicottero Vacanza', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (61, 8, 325, 'M', 'Costumi da uomo Cordone stampa dappertutto Vacanza', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (62, 8, 325, 'M', 'Costumi da uomo Cordone Tropicale Vacanza', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (63, 14, 325, 'M', 'Costumi da uomo Creste Lettere Vacanza', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (64, 15, 325, 'M', 'Shorts a righe da spiaggia da uomo con coulisse', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (65, 12, 325, 'M', 'Shorts da bagno con coulisse a righe', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (66, 14, 325, 'M', 'Shorts da spiaggia stampato con coulisse da uomo', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (67, 11, 325, 'M', 'Trunks da nuoto a righe ananas', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (68, 15, 325, 'M', 'Trunks da nuoto con coulisse grafica fumetto', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (69, 15, 325, 'M', 'Trunks da nuoto con coulisse ombre da uomo', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (70, 15, 325, 'M', 'Trunks da nuoto con coulisse ombre da uomo', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (71, 15, 325, 'M', 'Trunks da nuoto con coulisse ombre da uomo', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (72, 15, 325, 'M', 'Trunks da nuoto con tasca e coulisse', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (73, 15, 325, 'M', 'Trunks da nuoto con tasca e coulisse', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (74, 15, 325, 'M', 'Trunks da nuoto con tasca e coulisse', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (75, 15, 325, 'M', 'Trunks da nuoto con tasca e coulisse', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (76, 15, 325, 'M', 'Trunks da nuoto con tasca e coulisse', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (77, 11, 325, 'M', 'Trunks da nuoto stampato', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (78, 17, 325, 'M', 'Felpa con cappuccio con coulisse e stampa fulmine da uomo', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (79, 20, 325, 'M', 'Felpa con cappuccio e coulisse con stampa lettera da uomo', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (80, 17, 325, 'M', 'Felpa con cappuccio e coulisse grafica lettera', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (81, 15, 325, 'M', 'Felpa con cappuccio e manica raglan e fascia neon e fumetto grafico da uomo', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (82, 18, 325, 'M', 'Felpa con cappuccio e slogan grafico', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (83, 19, 325, 'M', 'Felpa con cappuccio e tasca con stampa floreale e giapponese', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (84, 19, 325, 'M', 'Felpa con cappuccio e tasca con stampa floreale e giapponese', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (85, 15, 325, 'M', 'Felpa con stampa drago e lettera cinese', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (86, 15, 325, 'M', 'Felpa con stampa floreale e slogan da uomo', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (87, 18, 325, 'M', 'Felpa con stampa mano da uomo', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (88, 20, 325, 'M', 'Felpe da uomo Cordone Floreale Strada', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (89, 20, 325, 'M', 'Felpe da uomo Cordone Floreale Strada', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (90, 20, 325, 'M', 'Felpe da uomo Cordone Floreale Strada', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (91, 18, 325, 'M', 'Felpe da uomo Cordone Grafico Strada', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (92, 18, 325, 'M', 'Felpe da uomo Cordone Grafico Strada', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (93, 24, 325, 'M', 'Felpe da uomo Cordone Lettere College', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (94, 22, 325, 'M', 'Felpe da uomo Cordone Lettere Strada', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (95, 20, 325, 'M', 'Felpe da uomo Cordone slogan College', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (96, 17, 325, 'M', 'Felpe da uomo Grafico Strada', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (97, 14, 325, 'M', 'Felpe da uomo Lettere Casual', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (98, 20, 325, 'M', 'Felpe da uomo Ricamo quadri College', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (99, 15, 325, 'M', 'Felpa con cappuccio e coulisse grafica fumetto', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (100, 15, 325, 'M', 'Felpa con cappuccio e coulisse grafica fumetto', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (101, 15, 325, 'M', 'Felpa con cappuccio e coulisse grafica fumetto', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (102, 22, 325, 'M', 'Shorts da pista monocolore con vita con coulisse', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (103, 12, 325, 'M', 'Shorts da pista monocolore con vita con coulisse', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (104, 10, 325, 'M', 'Pantaloncini da uomo Cordone Fuoco Multicolore Strada', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (105, 18, 325, 'M', 'Pantaloncini da uomo Cordone Grafico nero Casual', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (106, 10, 325, 'M', 'Pantaloncini da uomo Cordone Lettere Casual NASA', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (107, 12, 325, 'M', 'Pantaloncini da uomo militare', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (108, 15, 325, 'M', 'Pantaloncini da uomo Tasca quadri Casual', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (109, 9, 325, 'M', 'Pantaloncini da uomo Tasca slogan Casual', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (110, 11, 325, 'M', 'Pantaloncini da uomo Tasca slogan Casual', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (111, 15, 325, 'M', 'Shorts bermuda con fasce e patta laterale', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (112, 16, 325, 'M', 'Shorts con coulisse in vita con tasca e patta laterale', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (113, 14, 325, 'M', 'Shorts con coulisse in vita con tasca e patta laterale', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (114, 10, 325, 'M', 'Shorts da uomo con vita elastica e stampa grafica', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (115, 23, 325, 'M', 'Pantaloni a quadri con orlo con coulisse', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (116, 15, 325, 'M', 'Pantaloni a righe con coulisse in vita', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (117, 17, 325, 'M', 'Pantaloni cargo con tasca con patta con grafica di lettere', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (118, 27, 325, 'M', 'Pantaloni cargo con tasca con patta con grafica di lettere', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (119, 22, 325, 'M', 'Pantaloni cargo con tasca e stampa mimetico', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (120, 16, 325, 'M', 'Pantaloni cargo con tasca e stampa mimetico', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (121, 17, 325, 'M', 'Pantaloni cargo con tasca e stampa mimetico', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (122, 23, 325, 'M', 'Pantaloni con stampa fulmine da uomo', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (123, 18, 325, 'M', 'Pantaloni con stampa fulmine da uomo', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (124, 15, 325, 'M', 'Pantaloni con tasca inclinata grafica con lettera', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (125, 26, 325, 'M', 'Pantaloni con toppa stella con fibbia', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (126, 21, 325, 'M', 'Pantaloni con toppa stella con fibbia', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (127, 24, 325, 'M', 'Pantaloni da uomo Cordone Colore unico Casual', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (128, 19, 325, 'M', 'Pantaloni da uomo Tasca Lettere nero Strada', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (129, 18, 325, 'M', 'Pantaloni di carota con coulisse in vita cachi', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (130, 24, 325, 'M', 'Pantaloni pantofole con pannello a contrasto', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (131, 22, 325, 'M', 'Pantaloni sportivi con stampa di slogan e grafica', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (132, 14, 325, 'M', 'Polo da uomo Bottoni A strisce Blu Navy Ufficio', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (133, 12, 325, 'M', 'Polo comoda monocolore', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (134, 12, 325, 'M', 'Camicia polo da uomo con bordo a contrasto e ricamo', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (135, 13, 325, 'M', 'Camicia polo con bordo a contrasto da uomo', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (136, 12, 325, 'M', 'Camicia polo da uomo con stampa giraffa & a righe', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (137, 15, 325, 'M', 'Camicia polo da uomo con collo dritto e bottone mezzo', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (138, 15, 325, 'M', 'Camicia polo da uomo con collo dritto e bottone mezzo', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (139, 15, 325, 'M', 'Camicia polo da uomo con collo dritto e bottone mezzo', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (140, 15, 325, 'M', 'Camicia polo da uomo con collo dritto e bottone mezzo', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (141, 15, 325, 'M', 'Maglietta con bottone un quarto con pannello a contrasto', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (142, 14, 325, 'M', 'Camicia polo con ricamo lettera', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (143, 14, 325, 'M', 'Camicia polo con ricamo lettera', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (144, 14, 325, 'M', 'Camicia polo a quadri in contrasto da uomo', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (145, 14, 325, 'M', 'Camicia polo a quadri in contrasto da uomo', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (146, 15, 325, 'M', 'Camicia polo da uomo con bordo a righe a contrasto', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (147, 15, 325, 'M', 'Camicia polo da uomo con bordo a righe a contrasto', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (148, 14, 325, 'M', 'Camicia polo con ricamo e collo a contrasto', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (149, 15, 325, 'M', 'Camicia polo con stampa foglia e collo a contrasto', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (150, 13, 325, 'M', 'Camicia polo con blocchi di colore da uomo', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (151, 13, 325, 'M', 'Camicia polo con blocchi di colore da uomo', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (152, 13, 325, 'M', 'Polo con orlo a righe', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (153, 13, 325, 'M', 'Polo con orlo a righe', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (154, 13, 325, 'M', 'Polo con orlo a righe', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (155, 13, 325, 'M', 'Polo con orlo a righe', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (156, 15, 325, 'M', 'Polo da uomo Bottoni A strisce Casual', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (157, 14, 325, 'M', 'Polo da uomo Bottone frontale Blocchi di colore Casual', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (158, 14, 325, 'M', 'Polo con nastro a righe', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (159, 13, 325, 'M', 'Polo da uomo Bordo a contrasto Blu Navy Ufficio', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (160, 11, 325, 'M', 'Camicia polo monocolore', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (161, 11, 325, 'M', 'Camicia polo monocolore', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (162, 11, 325, 'M', 'Camicia polo monocolore', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (163, 10, 325, 'M', 'Camicia polo con manica corta', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (164, 14, 325, 'M', 'Maglietta polo con collo a contrasto', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (165, 13, 325, 'M', 'Camicia monocolore con spalle cadenti', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (166, 14, 325, 'M', 'Camicia a quadri', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (167, 14, 325, 'M', 'Camicia a quadri', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (168, 14, 325, 'M', 'Camicia con bottone con tasca frontale', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (169, 14, 325, 'M', 'Camicia con bottone con tasca frontale', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (170, 16, 325, 'M', 'Camicia a catena e cranio con bottone da uomo', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (171, 13, 325, 'M', 'Camicia con bottone frontale con stampa di patchwork', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (172, 14, 325, 'M', 'Camicie da uomo Bordo a contrasto College', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (173, 10, 325, 'M', 'Kimono con stampa di graffiti', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (174, 19, 325, 'M', 'Camicia a quadri in flanella con bottone', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (175, 19, 325, 'M', 'Camicia a quadri in flanella con bottone', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (176, 19, 325, 'M', 'Camicia a quadri in flanella con bottone', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (177, 10, 325, 'M', 'Kimono con stampa drago cinese', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (178, 19, 325, 'M', 'Camicie da uomo Tasca Colore unico Casual', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (179, 19, 325, 'M', 'Camicie da uomo Tasca Colore unico Casual', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (180, 15, 325, 'M', 'Kimono da uomo con stampa halloween', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (181, 15, 325, 'M', 'Kimono da uomo con stampa halloween', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (182, 13, 325, 'M', 'Camicia con bottone e stamap paisley', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (183, 13, 325, 'M', 'Camicia con bottone e stamap paisley', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (184, 11, 325, 'M', 'Camicia con fiamme', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (185, 15, 325, 'M', 'Camicie da uomo Bottone frontale Macchia di colore Vacanza', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (186, 12, 325, 'M', 'Camicia stampa draghi', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (187, 12, 325, 'M', 'Camicia stampa draghi', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (188, 18, 325, 'M', 'Camicie da uomo Bottone frontale Colore unico', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (189, 18, 325, 'M', 'Camicie da uomo Bottone frontale Colore unico', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (190, 18, 325, 'M', 'Camicie da uomo Bottone frontale Colore unico', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (191, 14, 325, 'M', 'Camicia con toppa con collo a revere', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (192, 14, 325, 'M', 'Camicia con toppa con collo a revere', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (193, 13, 325, 'M', 'Camicia con bottone con stampa paisley', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (194, 11, 325, 'M', 'Kimono bicolore con spalle cadenti', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (195, 15, 325, 'M', 'Camicie da uomo Animale Strada', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (196, 11, 325, 'M', 'Camicia a righe', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (197, 9, 325, 'M', 'Maglietta cest la vie', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (198, 8, 325, 'M', 'Maglietta farfalla', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (199, 8, 325, 'M', 'Maglietta alieni', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (200, 10, 325, 'M', 'Maglietta con stampa creato', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (201, 10, 325, 'M', 'Maglietta con stampa creato', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (202, 11, 325, 'M', 'Maglietta stampa scritte', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (203, 12, 325, 'M', 'Maglietta stampa occhi', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (204, 12, 325, 'M', 'Maglietta stampa occhi', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (205, 12, 325, 'M', 'Maglietta stampa occhi', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (206, 11, 325, 'M', 'Maglietta con lacci', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (207, 10, 325, 'M', 'Maglietta con fulmini', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (208, 9, 325, 'M', 'Maglietta stampa tsunami', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (209, 9, 325, 'M', 'Maglietta stampa tsunami', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (210, 9, 325, 'M', 'Maglietta stampa tsunami', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (211, 18, 325, 'M', 'Magliette x2', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (212, 18, 325, 'M', 'Magliette x2', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (213, 18, 325, 'M', 'Magliette x2', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (214, 11, 325, 'M', 'Maglietta con stampe e scritte', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (215, 11, 325, 'M', 'Maglietta con stampe e scritte', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (216, 8, 325, 'M', 'Maglietta foresta', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (217, 9, 325, 'M', 'Maglietta con stampe', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (218, 7, 325, 'M', 'Maglietta be nice', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (219, 7, 325, 'M', 'Maglietta be nice', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (220, 7, 325, 'M', 'Maglietta be nice', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (221, 9, 325, 'M', 'Maglietta stampe giapponesi', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (222, 9, 325, 'M', 'Maglietta stampe giapponesi', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (223, 11, 325, 'M', 'Maglietta con rosa', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (224, 11, 325, 'M', 'Maglietta con rosa', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (225, 11, 325, 'M', 'Maglietta con rosa', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (226, 12, 325, 'M', 'Maglietta con drago', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (227, 13, 325, 'M', 'Maglietta week', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (228, 13, 325, 'M', 'Maglietta week', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (229, 8, 325, 'M', 'Maglietta mappa', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (230, 8, 325, 'M', 'Maglietta mappa', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (231, 8, 325, 'M', 'Maglietta mappa', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (232, 13, 325, 'M', 'Maglietta palme', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (233, 11, 325, 'M', 'Maglietta a righe', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (234, 11, 325, 'M', 'Maglietta a righe', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (235, 11, 325, 'M', 'Maglietta a righe', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (236, 27, 325, 'F', 'Cappotti Tasca Colore unico Casual ', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (237, 27, 325, 'F', 'Cappotti Tasca Colore unico Casual', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (238, 27, 325, 'F', 'Cappotti Tasca Colore unico Casual', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (239, 27, 325, 'F', 'Cappotti Tasca Colore unico Casual', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (240, 20, 325, 'F', 'Cappotto a quadri con spalle cadenti e orlo curvo', 0, 1);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (241, 27, 325, 'F', 'Cappotto a quadri con tasca e orlo curvo', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (242, 27, 325, 'F', 'Cappotto a quadri con tasca e orlo curvo', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (243, 27, 325, 'F', 'Cappotto a quadri con tasca e orlo curvo', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (244, 9, 325, 'F', 'Cappotto aperto frontale con dettaglio tasca', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (245, 16, 325, 'F', 'Cappotto con cappuccio con bottone e coulisse', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (246, 16, 325, 'F', 'Cappotto con cappuccio con bottone e coulisse', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (247, 26, 325, 'F', 'Cappotto con colletto a revers con monopetto ', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (248, 26, 325, 'F', 'Cappotto con colletto a revers con monopetto ', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (249, 19, 325, 'F', 'Cappotto con spalle cadenti e bottone a quadri ', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (250, 19, 325, 'F', 'Cappotto con spalle cadenti e bottone a quadri ', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (251, 19, 325, 'F', 'Cappotto con spalle cadenti e bottone a quadri ', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (252, 21, 325, 'F', 'Cappotto con tasca e collo a scialle ', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (253, 21, 325, 'F', 'Cappotto con tasca e collo a scialle ', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (254, 21, 325, 'F', 'Cappotto con tasca e collo a scialle ', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (255, 21, 325, 'F', 'Cappotto con tasca e collo a scialle ', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (256, 17, 325, 'F', 'Cappotto con tasca sul lato e doppio petto', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (257, 17, 325, 'F', 'Cappotto con tasca sul lato e doppio petto', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (258, 22, 325, 'F', 'Cappotto in pelle PU con tasca e monopetto', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (259, 19, 325, 'F', 'Cappotto monocolore con spalle cadenti e bottone', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (260, 19, 325, 'F', 'Cappotto monocolore con spalle cadenti e bottone', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (261, 20, 325, 'F', 'Cappotto pea con collo a bavero e doppio petto', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (262, 20, 325, 'F', 'Cappotto pea con collo a bavero e doppio petto', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (263, 20, 325, 'F', 'Cappotto pea con collo a bavero e doppio petto', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (264, 25, 325, 'F', 'Cappotto trench con cinture e doppio petto', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (265, 16, 325, 'F', 'Giacca a vento con cappuccio e coulisse con zip ', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (266, 13, 325, 'F', 'Giacca a vento con cappuccio riflessivo e zipper up', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (267, 9, 325, 'F', 'Giacca bomber con zip e stampa floreale', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (268, 9, 325, 'F', 'Giacca bomber con zip e stampa floreale', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (269, 12, 325, 'F', 'Giacca bomber monocolore con dettaglio cerniera', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (270, 12, 325, 'F', 'Giacca bomber monocolore con dettaglio cerniera', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (271, 12, 325, 'F', 'Giacca bomber monocolore con dettaglio cerniera', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (272, 20, 325, 'F', 'Giacca con cappuccio con coulisse con tasca frontale con zip', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (273, 14, 325, 'F', 'Giacca con cappuccio e coulisse e zipper up', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (274, 14, 325, 'F', 'Giacca con cappuccio e coulisse e zipper up', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (275, 14, 325, 'F', 'Giacca con cappuccio e coulisse e zipper up', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (276, 34, 325, 'F', 'Giacca da ciclisimo in PU con zip e collo a bavero', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (277, 15, 325, 'F', 'Giacca in PU con monopetto', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (278, 17, 325, 'F', 'Giacca riflessivo con zip color block', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (279, 20, 325, 'F', 'Giacche Bottone frontale Blocchi di colore Sportivo', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (280, 17, 325, 'F', 'Giacche Bottone frontale Lettere Sportivo', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (281, 29, 325, 'F', 'Giacche Cerniera Colore unico Casual', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (282, 29, 325, 'F', 'Giacche Cerniera Colore unico Casual', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (283, 29, 325, 'F', 'Giacche Cerniera Colore unico Casual', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (284, 11, 325, 'F', 'Bikini mutandine con stampa palma e top con cinturino regolabile ', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (285, 11, 325, 'F', 'Bikini mutandine con stampa palma e top con cinturino regolabile ', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (286, 11, 325, 'F', 'Costume da bagno bikini bicolore con taglio alto', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (287, 11, 325, 'F', 'Costume da bagno bikini bicolore con taglio alto', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (288, 10, 325, 'F', 'Costume da bagno bikini con stampa foglia ', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (289, 10, 325, 'F', 'Costume da bagno bikini con stampa foglia ', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (290, 10, 325, 'F', 'Costume da bagno bikini con stampa foglia ', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (291, 10, 325, 'F', 'Costume da bagno bikini con taglio alto', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (292, 13, 325, 'F', 'Costume da bagno bikini con vita alta e nodo di blocchi di colore', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (293, 13, 325, 'F', 'Costume da bagno bikini con vita alta e nodo di blocchi di colore', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (294, 11, 325, 'F', 'Costume da bagno bikini nodo laterale incrociato leopardo', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (295, 10, 325, 'F', 'Costume da bagno bikini semplice', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (296, 11, 325, 'F', 'Costume da bagno monocolore con cut alto', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (297, 12, 325, 'F', 'Set bibkini top triangolo in raso e perizoma', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (298, 10, 325, 'F', 'Set bikini top halter con lacci e nodo laterale', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (299, 10, 325, 'F', 'Set bikini top halter con lacci e nodo laterale', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (300, 10, 325, 'F', 'Set bikini top halter con lacci e nodo laterale', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (301, 11, 325, 'F', 'Sets bikini Colore unico', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (302, 11, 325, 'F', 'Sets bikini Colore unico', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (303, 11, 325, 'F', 'Sets bikini Colore unico', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (304, 11, 325, 'F', 'Sets bikini Spalline incrociate Colore unico', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (305, 12, 325, 'F', 'Sets bikini Tie Dye Sexy', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (306, 12, 325, 'F', 'Sets bikini Tie Dye Sexy', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (307, 10, 325, 'F', 'Sets bikini Torsate Colore unico Carino', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (308, 10, 325, 'F', 'Sets bikini Torsate Colore unico Carino', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (309, 10, 325, 'F', 'Sets bikini Torsate Colore unico Carino', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (310, 10, 325, 'F', 'Sets bikini Torsate Colore unico Carino', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (311, 10, 325, 'F', 'Sets bikini Torsate Colore unico Carino', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (312, 12, 325, 'F', 'Sets bikini Torsate Tropicale Sexy', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (313, 11, 325, 'F', 'Sets bikini Volanti Colore unico Carino', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (314, 11, 325, 'F', 'Sets bikini Volanti Colore unico Carino', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (315, 10, 325, 'F', 'Sets bikini Volanti Colore unico Sexy', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (316, 10, 325, 'F', 'Sets bikini Volanti Colore unico Sexy', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (317, 10, 325, 'F', 'Sets bikini Volanti Colore unico Sexy', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (318, 12, 325, 'F', 'Costume da bagno a croce con rete', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (319, 12, 325, 'F', 'Costume da bagno bicolore con monospalle', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (320, 12, 325, 'F', 'Costume da bagno bicolore con monospalle', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (321, 12, 325, 'F', 'Costume da bagno bicolore con monospalle', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (322, 12, 325, 'F', 'Costume da bagno bicolore con monospalle', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (323, 12, 325, 'F', 'Costume da bagno intero bandeau in tulle a contrasto', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (324, 12, 325, 'F', 'Costume da bagno intero con capestro e collo profondo e stampa tropicale', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (325, 13, 325, 'F', 'Costume da bagno intero con orlo arricciato', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (326, 12, 325, 'F', 'Costume da bagno intero con taglio ', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (327, 12, 325, 'F', 'Costume da bagno intero con taglio ', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (328, 12, 325, 'F', 'Costume da bagno intero con taglio ', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (329, 11, 325, 'F', 'Costume da bagno intero floreale con appliques', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (330, 13, 325, 'F', 'Costume da bagno intero halter plissettato', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (331, 13, 325, 'F', 'Costume da bagno intero halter plissettato', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (332, 13, 325, 'F', 'Costume da bagno intero halter plissettato', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (333, 14, 325, 'F', 'Costume da bagno intero incrociato con nodo frontale', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (334, 14, 325, 'F', 'Costume da bagno intero incrociato con nodo frontale', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (335, 11, 325, 'F', 'Intero Spalline incrociate Colore unico Casual', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (336, 11, 325, 'F', 'Intero Spalline incrociate Colore unico Casual', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (337, 12, 325, 'F', 'Monokini tropicale halter incrociato con cut out in vita', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (338, 12, 325, 'F', 'Tuta con cut out effetto serpente', 0, 5);