USE toj_sitoweb;
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (1, 38, 325, 'M', 'Cappotti da uomo Tasca Colore unico Ufficio', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (2, 38, 325, 'M', 'Cappotti da uomo Tasca Colore unico Ufficio', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (3, 41, 325, 'M', 'Cappotto a quadri con bottone da uomo', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (4, 30, 325, 'M', 'Cappotto a quadri con bottone e collo a V dentellato', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (5, 27, 325, 'M', 'Cappotto a quadri con doppia tasca', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (6, 44, 325, 'M', 'Cappotto con cappuccio con doppio petto da uomo', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (7, 37, 325, 'M', 'Cappotto con monopetto e tasca laterale', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (8, 71, 325, 'M', 'Cappotto con tasca e pulsante clacson', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (9, 35, 325, 'M', 'Cappotto da uomo con cappuccio e tasca frontale con patta', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (10, 37, 325, 'M', 'Cappotto da uomo con dettaglio di patta', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (11, 71, 325, 'M', 'Cappotto da uomo con doppia tasca monopetto', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (12, 36, 325, 'M', 'Cappotto monopetto da uomo con colletto dentellato grigio', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (13, 26, 325, 'M', 'Cappotto teddy con doppio petto', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (14, 41, 325, 'M', 'Cappotto da uomo con spalle scoperte', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (15, 34, 325, 'M', 'Cappotto da uomo in pile color block con patch a lettere con cerniera', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (16, 40, 325, 'M', 'Cappotto da uomo in pile con motivo a quadri e tasca con patta', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (17, 37, 325, 'M', 'Cappotto da uomo in tinta unita con revers', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (18, 83, 325, 'M', 'Cappotto da uomo in tinta unita con risvolto abbottonato', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (19, 36, 325, 'M', 'Cappotto da uomo in tinta unita con risvolto abbottonato', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (20, 36, 325, 'M', 'Overcoat con bottone e patta da uomo', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (21, 73, 325, 'M', 'Soprabito anteriore con tasca scozzese da uomo', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (22, 27, 325, 'M', 'Cappotto monopetto da uomo con colletto dentellato grigio', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (23, 28, 325, 'M', 'Bomber da uomo con fodera in pile semplice', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (24, 31, 325, 'M', 'Bomber da uomo con tasca obliqua e zip', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (25, 38, 325, 'M', 'Bomber trapuntato da uomo con zip', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (26, 38, 325, 'M', 'Bomber trapuntato da uomo con zip', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (27, 17, 325, 'M', 'Giacca da uomo Cerniera Blocchi di colore Bianco e Nero College', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (28, 27, 325, 'M', 'Giacca da uomo Cerniera Colore unico Verde militare College', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (29, 24, 325, 'M', 'Giacca da uomo Cordone Colore unico Grigio', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (30, 28, 325, 'M', 'Giacca a vento con cappuccio e zip mimetico', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (31, 29, 325, 'M', 'Giacca a vento con tasca e patta gialla', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (32, 34, 325, 'M', 'Giacca a vento con zip color block', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (33, 43, 325, 'M', 'Giacca a vento da uomo con bottoni', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (34, 21, 325, 'M', 'Giacca bomber con grafica di lettere senza maglietta', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (35, 22, 325, 'M', 'Giacca bomber con ricamo lettera', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (36, 22, 325, 'M', 'Giacca bomber con ricamo lettera', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (37, 22, 325, 'M', 'Giacca bomber con ricamo lettera', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (38, 22, 325, 'M', 'Giacca bomber con stampa mimetica', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (39, 21, 325, 'M', 'Giacca bomber con zip', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (40, 24, 325, 'M', 'Giacca con cappuccio e coulisse con zip color black', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (41, 43, 325, 'M', 'Giacca da ciclisimo con collo a bavero in PU', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (42, 59, 325, 'M', 'Giacca da moto in pelle PU con cerniera frontale da uomo', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (43, 28, 325, 'M', 'Giacca da uomo con cappuccio e zip con coulisse', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (44, 28, 325, 'M', 'Giacca da uomo con cappuccio e zip con coulisse', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (45, 37, 325, 'M', 'Giacca da uomo in cotone con cappuccio, tasca laterale con cerniera e dettaglio in fettuccia', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (46, 24, 325, 'M', 'Giacca mimetica con zip', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (47, 44, 325, 'M', 'Giacca piumino con toppa', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (48, 9, 325, 'M', 'Costume da bagno con coulisse con stampa tropicale', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (49, 15, 325, 'M', 'Costume da bagno con coulisse con tasca con zip', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (50, 15, 325, 'M', 'Costume da bagno con coulisse con tasca con zip', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (51, 15, 325, 'M', 'Costume da bagno con coulisse con tasca con zip', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (52, 15, 325, 'M', 'Costume da bagno con coulisse con tasca con zip', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (53, 12, 325, 'M', 'Costume da bagno con coulisse in vita grafica con lettera blu', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (54, 12, 325, 'M', 'Costume da bagno con coulisse in vita grafica con lettera', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (55, 12, 325, 'M', 'Costume da bagno con coulisse in vita grafica con lettera', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (56, 9, 325, 'M', 'Costume da bagno da uomo con coulisse e stampa albero di palma', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (57, 14, 325, 'M', 'Costume da bagno da uomo con stampa fenicottero', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (58, 14, 325, 'M', 'Costume da bagno da uomo con stampa fenicottero', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (59, 8, 325, 'M', 'Costumi da uomo Animale Vacanza', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (60, 14, 325, 'M', 'Costumi da uomo Cordone Fenicottero Vacanza', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (61, 8, 325, 'M', 'Costumi da uomo Cordone stampa dappertutto Vacanza', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (62, 8, 325, 'M', 'Costumi da uomo Cordone Tropicale Vacanza', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (63, 14, 325, 'M', 'Costumi da uomo Creste Lettere Vacanza', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (64, 15, 325, 'M', 'Shorts a righe da spiaggia da uomo con coulisse', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (65, 12, 325, 'M', 'Shorts da bagno con coulisse a righe', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (66, 14, 325, 'M', 'Shorts da spiaggia stampato con coulisse da uomo', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (67, 11, 325, 'M', 'Trunks da nuoto a righe ananas', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (68, 15, 325, 'M', 'Trunks da nuoto con coulisse grafica fumetto', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (69, 15, 325, 'M', 'Trunks da nuoto con coulisse ombre da uomo', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (70, 15, 325, 'M', 'Trunks da nuoto con coulisse ombre da uomo', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (71, 15, 325, 'M', 'Trunks da nuoto con coulisse ombre da uomo', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (72, 15, 325, 'M', 'Trunks da nuoto con tasca e coulisse', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (73, 15, 325, 'M', 'Trunks da nuoto con tasca e coulisse', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (74, 15, 325, 'M', 'Trunks da nuoto con tasca e coulisse', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (75, 15, 325, 'M', 'Trunks da nuoto con tasca e coulisse', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (76, 15, 325, 'M', 'Trunks da nuoto con tasca e coulisse', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (77, 11, 325, 'M', 'Trunks da nuoto stampato', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (78, 17, 325, 'M', 'Felpa con cappuccio con coulisse e stampa fulmine da uomo', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (79, 20, 325, 'M', 'Felpa con cappuccio e coulisse con stampa lettera da uomo', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (80, 17, 325, 'M', 'Felpa con cappuccio e coulisse grafica lettera', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (81, 15, 325, 'M', 'Felpa con cappuccio e manica raglan e fascia neon e fumetto grafico da uomo', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (82, 18, 325, 'M', 'Felpa con cappuccio e slogan grafico', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (83, 19, 325, 'M', 'Felpa con cappuccio e tasca con stampa floreale e giapponese', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (84, 19, 325, 'M', 'Felpa con cappuccio e tasca con stampa floreale e giapponese', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (85, 15, 325, 'M', 'Felpa con stampa drago e lettera cinese', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (86, 15, 325, 'M', 'Felpa con stampa floreale e slogan da uomo', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (87, 18, 325, 'M', 'Felpa con stampa mano da uomo', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (88, 20, 325, 'M', 'Felpe da uomo Cordone Floreale Strada', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (89, 20, 325, 'M', 'Felpe da uomo Cordone Floreale Strada', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (90, 20, 325, 'M', 'Felpe da uomo Cordone Floreale Strada', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (91, 18, 325, 'M', 'Felpe da uomo Cordone Grafico Strada', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (92, 18, 325, 'M', 'Felpe da uomo Cordone Grafico Strada', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (93, 24, 325, 'M', 'Felpe da uomo Cordone Lettere College', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (94, 22, 325, 'M', 'Felpe da uomo Cordone Lettere Strada', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (95, 20, 325, 'M', 'Felpe da uomo Cordone slogan College', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (96, 17, 325, 'M', 'Felpe da uomo Grafico Strada', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (97, 14, 325, 'M', 'Felpe da uomo Lettere Casual', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (98, 20, 325, 'M', 'Felpe da uomo Ricamo quadri College', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (99, 15, 325, 'M', 'Felpa con cappuccio e coulisse grafica fumetto', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (100, 15, 325, 'M', 'Felpa con cappuccio e coulisse grafica fumetto', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (101, 15, 325, 'M', 'Felpa con cappuccio e coulisse grafica fumetto', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (102, 22, 325, 'M', 'Shorts da pista monocolore con vita con coulisse', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (103, 12, 325, 'M', 'Shorts da pista monocolore con vita con coulisse', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (104, 10, 325, 'M', 'Pantaloncini da uomo Cordone Fuoco Multicolore Strada', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (105, 18, 325, 'M', 'Pantaloncini da uomo Cordone Grafico nero Casual', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (106, 10, 325, 'M', 'Pantaloncini da uomo Cordone Lettere Casual NASA', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (107, 12, 325, 'M', 'Pantaloncini da uomo militare', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (108, 15, 325, 'M', 'Pantaloncini da uomo Tasca quadri Casual', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (109, 9, 325, 'M', 'Pantaloncini da uomo Tasca slogan Casual', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (110, 11, 325, 'M', 'Pantaloncini da uomo Tasca slogan Casual', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (111, 15, 325, 'M', 'Shorts bermuda con fasce e patta laterale', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (112, 16, 325, 'M', 'Shorts con coulisse in vita con tasca e patta laterale', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (113, 14, 325, 'M', 'Shorts con coulisse in vita con tasca e patta laterale', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (114, 10, 325, 'M', 'Shorts da uomo con vita elastica e stampa grafica', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (115, 23, 325, 'M', 'Pantaloni a quadri con orlo con coulisse', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (116, 15, 325, 'M', 'Pantaloni a righe con coulisse in vita', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (117, 17, 325, 'M', 'Pantaloni cargo con tasca con patta con grafica di lettere', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (118, 27, 325, 'M', 'Pantaloni cargo con tasca con patta con grafica di lettere', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (119, 22, 325, 'M', 'Pantaloni cargo con tasca e stampa mimetico', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (120, 16, 325, 'M', 'Pantaloni cargo con tasca e stampa mimetico', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (121, 17, 325, 'M', 'Pantaloni cargo con tasca e stampa mimetico', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (122, 23, 325, 'M', 'Pantaloni con stampa fulmine da uomo', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (123, 18, 325, 'M', 'Pantaloni con stampa fulmine da uomo', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (124, 15, 325, 'M', 'Pantaloni con tasca inclinata grafica con lettera', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (125, 26, 325, 'M', 'Pantaloni con toppa stella con fibbia', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (126, 21, 325, 'M', 'Pantaloni con toppa stella con fibbia', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (127, 24, 325, 'M', 'Pantaloni da uomo Cordone Colore unico Casual', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (128, 19, 325, 'M', 'Pantaloni da uomo Tasca Lettere nero Strada', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (129, 18, 325, 'M', 'Pantaloni di carota con coulisse in vita cachi', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (130, 24, 325, 'M', 'Pantaloni pantofole con pannello a contrasto', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (131, 22, 325, 'M', 'Pantaloni sportivi con stampa di slogan e grafica', 0, 11);