USE toj_sitoweb;
INSERT INTO colore (cod_esadecimale, Nome) VALUES ('#000000', 'Nero');
INSERT INTO colore (cod_esadecimale, Nome) VALUES ('#000080', 'Blu');
INSERT INTO colore (cod_esadecimale, Nome) VALUES ('#006400', 'Verde scuro');
INSERT INTO colore (cod_esadecimale, Nome) VALUES ('#008000', 'Verde');
INSERT INTO colore (cod_esadecimale, Nome) VALUES ('#00BFFF', 'Azzurro');
INSERT INTO colore (cod_esadecimale, Nome) VALUES ('#183653', 'Blu mimetico');
INSERT INTO colore (cod_esadecimale, Nome) VALUES ('#30D5C8', 'Turchese');
INSERT INTO colore (cod_esadecimale, Nome) VALUES ('#696969', 'Grigio scuro');
INSERT INTO colore (cod_esadecimale, Nome) VALUES ('#6B8E23', 'Verde militare');
INSERT INTO colore (cod_esadecimale, Nome) VALUES ('#800000', 'Bordeaux');
INSERT INTO colore (cod_esadecimale, Nome) VALUES ('#8B4513', 'Marrone');
INSERT INTO colore (cod_esadecimale, Nome) VALUES ('#90EE90', 'Verde chiaro');
INSERT INTO colore (cod_esadecimale, Nome) VALUES ('#9400D3', 'Viola');
INSERT INTO colore (cod_esadecimale, Nome) VALUES ('#9C9C9C', 'Grigio');
INSERT INTO colore (cod_esadecimale, Nome) VALUES ('#C19A6B', 'Cammello');
INSERT INTO colore (cod_esadecimale, Nome) VALUES ('#DCDCDC', 'Grigio chiaro');
INSERT INTO colore (cod_esadecimale, Nome) VALUES ('#E1C699', 'Beige');
INSERT INTO colore (cod_esadecimale, Nome) VALUES ('#F0E68C', 'Cachi');
INSERT INTO colore (cod_esadecimale, Nome) VALUES ('#FF0000', 'Rosso');
INSERT INTO colore (cod_esadecimale, Nome) VALUES ('#FF1493', 'Fucsia');
INSERT INTO colore (cod_esadecimale, Nome) VALUES ('#FF8C00', 'Arancione');
INSERT INTO colore (cod_esadecimale, Nome) VALUES ('#FFC0CB', 'Rosa');
INSERT INTO colore (cod_esadecimale, Nome) VALUES ('#FFFF00', 'Giallo');
INSERT INTO colore (cod_esadecimale, Nome) VALUES ('#FFFFFF', 'Bianco');