INSERT INTO toj_sitoweb.categoria (ID_categoria, Nome) VALUES (1, 'Cappotti');
INSERT INTO toj_sitoweb.categoria (ID_categoria, Nome) VALUES (2, 'Giacche');
INSERT INTO toj_sitoweb.categoria (ID_categoria, Nome) VALUES (3, 'Costumi');
INSERT INTO toj_sitoweb.categoria (ID_categoria, Nome) VALUES (4, 'Bikini');
INSERT INTO toj_sitoweb.categoria (ID_categoria, Nome) VALUES (5, 'Intero');
INSERT INTO toj_sitoweb.categoria (ID_categoria, Nome) VALUES (6, 'Felpe');
INSERT INTO toj_sitoweb.categoria (ID_categoria, Nome) VALUES (7, 'Maglie');
INSERT INTO toj_sitoweb.categoria (ID_categoria, Nome) VALUES (8, 'Camicie');
INSERT INTO toj_sitoweb.categoria (ID_categoria, Nome) VALUES (9, 'Polo');
INSERT INTO toj_sitoweb.categoria (ID_categoria, Nome) VALUES (10, 'T-shirt');
INSERT INTO toj_sitoweb.categoria (ID_categoria, Nome) VALUES (11, 'Top');
INSERT INTO toj_sitoweb.categoria (ID_categoria, Nome) VALUES (12, 'Pantaloni lunghi');
INSERT INTO toj_sitoweb.categoria (ID_categoria, Nome) VALUES (13, 'Pantaloni corti');
INSERT INTO toj_sitoweb.categoria (ID_categoria, Nome) VALUES (14, 'Gonna corta');
INSERT INTO toj_sitoweb.categoria (ID_categoria, Nome) VALUES (15, 'Gonna lunga');