INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (1, 38, 325, 'M', 'Cappotti da uomo Tasca Colore unico Ufficio', 0, 1);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (2, 38, 325, 'M', 'Cappotti da uomo Tasca Colore unico Ufficio', 0, 1);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (3, 41, 325, 'M', 'Cappotto a quadri con bottone da uomo', 0, 1);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (4, 30, 325, 'M', 'Cappotto a quadri con bottone e collo a V dentellato', 0, 1);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (5, 27, 325, 'M', 'Cappotto a quadri con doppia tasca', 0, 1);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (6, 44, 325, 'M', 'Cappotto con cappuccio con doppio petto da uomo', 0, 1);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (7, 37, 325, 'M', 'Cappotto con monopetto e tasca laterale', 0, 1);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (8, 71, 325, 'M', 'Cappotto con tasca e pulsante clacson', 0, 1);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (9, 35, 325, 'M', 'Cappotto da uomo con cappuccio e tasca frontale con patta', 0, 1);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (10, 37, 325, 'M', 'Cappotto da uomo con dettaglio di patta', 0, 1);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (11, 71, 325, 'M', 'Cappotto da uomo con doppia tasca monopetto', 0, 1);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (12, 36, 325, 'M', 'Cappotto monopetto da uomo con colletto dentellato grigio', 0, 1);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (13, 26, 325, 'M', 'Cappotto teddy con doppio petto', 0, 1);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (14, 41, 325, 'M', 'Cappotto da uomo con spalle scoperte', 0, 1);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (15, 34, 325, 'M', 'Cappotto da uomo in pile color block con patch a lettere con cerniera', 0, 1);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (16, 40, 325, 'M', 'Cappotto da uomo in pile con motivo a quadri e tasca con patta', 0, 1);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (17, 37, 325, 'M', 'Cappotto da uomo in tinta unita con revers', 0, 1);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (18, 83, 325, 'M', 'Cappotto da uomo in tinta unita con risvolto abbottonato', 0, 1);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (19, 36, 325, 'M', 'Cappotto da uomo in tinta unita con risvolto abbottonato', 0, 1);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (20, 36, 325, 'M', 'Overcoat con bottone e patta da uomo', 0, 1);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (21, 73, 325, 'M', 'Soprabito anteriore con tasca scozzese da uomo', 0, 1);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (22, 27, 325, 'M', 'Cappotto monopetto da uomo con colletto dentellato grigio', 0, 1);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (23, 28, 325, 'M', 'Bomber da uomo con fodera in pile semplice', 0, 2);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (24, 31, 325, 'M', 'Bomber da uomo con tasca obliqua e zip', 0, 2);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (25, 38, 325, 'M', 'Bomber trapuntato da uomo con zip', 0, 2);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (26, 38, 325, 'M', 'Bomber trapuntato da uomo con zip', 0, 2);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (27, 17, 325, 'M', 'Giacca da uomo Cerniera Blocchi di colore Bianco e Nero College', 0, 2);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (28, 27, 325, 'M', 'Giacca da uomo Cerniera Colore unico Verde militare College', 0, 2);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (29, 24, 325, 'M', 'Giacca da uomo Cordone Colore unico Grigio', 0, 2);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (30, 28, 325, 'M', 'Giacca a vento con cappuccio e zip mimetico', 0, 2);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (31, 29, 325, 'M', 'Giacca a vento con tasca e patta gialla', 0, 2);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (32, 34, 325, 'M', 'Giacca a vento con zip color block', 0, 2);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (33, 43, 325, 'M', 'Giacca a vento da uomo con bottoni', 0, 2);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (34, 21, 325, 'M', 'Giacca bomber con grafica di lettere senza maglietta', 0, 2);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (35, 22, 325, 'M', 'Giacca bomber con ricamo lettera', 0, 2);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (36, 22, 325, 'M', 'Giacca bomber con ricamo lettera', 0, 2);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (37, 22, 325, 'M', 'Giacca bomber con ricamo lettera', 0, 2);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (38, 22, 325, 'M', 'Giacca bomber con stampa mimetica', 0, 2);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (39, 21, 325, 'M', 'Giacca bomber con zip', 0, 2);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (40, 24, 325, 'M', 'Giacca con cappuccio e coulisse con zip color black', 0, 2);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (41, 43, 325, 'M', 'Giacca da ciclisimo con collo a bavero in PU', 0, 2);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (42, 59, 325, 'M', 'Giacca da moto in pelle PU con cerniera frontale da uomo', 0, 2);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (43, 28, 325, 'M', 'Giacca da uomo con cappuccio e zip con coulisse', 0, 2);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (44, 28, 325, 'M', 'Giacca da uomo con cappuccio e zip con coulisse', 0, 2);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (45, 37, 325, 'M', 'Giacca da uomo in cotone con cappuccio, tasca laterale con cerniera e dettaglio in fettuccia', 0, 2);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (46, 24, 325, 'M', 'Giacca mimetica con zip', 0, 2);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (47, 44, 325, 'M', 'Giacca piumino con toppa', 0, 2);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (48, 9, 325, 'M', 'Costume da bagno con coulisse con stampa tropicale', 0, 3);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (49, 15, 325, 'M', 'Costume da bagno con coulisse con tasca con zip', 0, 3);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (50, 15, 325, 'M', 'Costume da bagno con coulisse con tasca con zip', 0, 3);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (51, 15, 325, 'M', 'Costume da bagno con coulisse con tasca con zip', 0, 3);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (52, 15, 325, 'M', 'Costume da bagno con coulisse con tasca con zip', 0, 3);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (53, 12, 325, 'M', 'Costume da bagno con coulisse in vita grafica con lettera blu', 0, 3);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (54, 12, 325, 'M', 'Costume da bagno con coulisse in vita grafica con lettera', 0, 3);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (55, 12, 325, 'M', 'Costume da bagno con coulisse in vita grafica con lettera', 0, 3);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (56, 9, 325, 'M', 'Costume da bagno da uomo con coulisse e stampa albero di palma', 0, 3);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (57, 14, 325, 'M', 'Costume da bagno da uomo con stampa fenicottero', 0, 3);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (58, 14, 325, 'M', 'Costume da bagno da uomo con stampa fenicottero', 0, 3);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (59, 8, 325, 'M', 'Costumi da uomo Animale Vacanza', 0, 3);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (60, 14, 325, 'M', 'Costumi da uomo Cordone Fenicottero Vacanza', 0, 3);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (61, 8, 325, 'M', 'Costumi da uomo Cordone stampa dappertutto Vacanza', 0, 3);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (62, 8, 325, 'M', 'Costumi da uomo Cordone Tropicale Vacanza', 0, 3);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (63, 14, 325, 'M', 'Costumi da uomo Creste Lettere Vacanza', 0, 3);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (64, 15, 325, 'M', 'Shorts a righe da spiaggia da uomo con coulisse', 0, 3);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (65, 12, 325, 'M', 'Shorts da bagno con coulisse a righe', 0, 3);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (66, 14, 325, 'M', 'Shorts da spiaggia stampato con coulisse da uomo', 0, 3);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (67, 11, 325, 'M', 'Trunks da nuoto a righe ananas', 0, 3);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (68, 15, 325, 'M', 'Trunks da nuoto con coulisse grafica fumetto', 0, 3);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (69, 15, 325, 'M', 'Trunks da nuoto con coulisse ombre da uomo', 0, 3);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (70, 15, 325, 'M', 'Trunks da nuoto con coulisse ombre da uomo', 0, 3);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (71, 15, 325, 'M', 'Trunks da nuoto con coulisse ombre da uomo', 0, 3);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (72, 15, 325, 'M', 'Trunks da nuoto con tasca e coulisse', 0, 3);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (73, 15, 325, 'M', 'Trunks da nuoto con tasca e coulisse', 0, 3);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (74, 15, 325, 'M', 'Trunks da nuoto con tasca e coulisse', 0, 3);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (75, 15, 325, 'M', 'Trunks da nuoto con tasca e coulisse', 0, 3);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (76, 15, 325, 'M', 'Trunks da nuoto con tasca e coulisse', 0, 3);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (77, 11, 325, 'M', 'Trunks da nuoto stampato', 0, 3);