USE toj_sitoweb;
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (1, 38, 325, 'M', 'Cappotti da uomo Tasca Colore unico Ufficio', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (2, 38, 325, 'M', 'Cappotti da uomo Tasca Colore unico Ufficio', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (3, 41, 325, 'M', 'Cappotto a quadri con bottone da uomo', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (4, 30, 325, 'M', 'Cappotto a quadri con bottone e collo a V dentellato', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (5, 27, 325, 'M', 'Cappotto a quadri con doppia tasca', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (6, 44, 325, 'M', 'Cappotto con cappuccio con doppio petto da uomo', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (7, 37, 325, 'M', 'Cappotto con monopetto e tasca laterale', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (8, 71, 325, 'M', 'Cappotto con tasca e pulsante clacson', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (9, 35, 325, 'M', 'Cappotto da uomo con cappuccio e tasca frontale con patta', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (10, 37, 325, 'M', 'Cappotto da uomo con dettaglio di patta', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (11, 71, 325, 'M', 'Cappotto da uomo con doppia tasca monopetto', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (12, 36, 325, 'M', 'Cappotto monopetto da uomo con colletto dentellato grigio', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (13, 26, 325, 'M', 'Cappotto teddy con doppio petto', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (14, 41, 325, 'M', 'Cappotto da uomo con spalle scoperte', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (15, 34, 325, 'M', 'Cappotto da uomo in pile color block con patch a lettere con cerniera', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (16, 40, 325, 'M', 'Cappotto da uomo in pile con motivo a quadri e tasca con patta', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (17, 37, 325, 'M', 'Cappotto da uomo in tinta unita con revers', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (18, 83, 325, 'M', 'Cappotto da uomo in tinta unita con risvolto abbottonato', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (19, 36, 325, 'M', 'Cappotto da uomo in tinta unita con risvolto abbottonato', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (20, 36, 325, 'M', 'Overcoat con bottone e patta da uomo', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (21, 73, 325, 'M', 'Soprabito anteriore con tasca scozzese da uomo', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (22, 27, 325, 'M', 'Cappotto monopetto da uomo con colletto dentellato grigio', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (23, 28, 325, 'M', 'Bomber da uomo con fodera in pile semplice', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (24, 31, 325, 'M', 'Bomber da uomo con tasca obliqua e zip', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (25, 38, 325, 'M', 'Bomber trapuntato da uomo con zip', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (26, 38, 325, 'M', 'Bomber trapuntato da uomo con zip', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (27, 17, 325, 'M', 'Giacca da uomo Cerniera Blocchi di colore Bianco e Nero College', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (28, 27, 325, 'M', 'Giacca da uomo Cerniera Colore unico Verde militare College', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (29, 24, 325, 'M', 'Giacca da uomo Cordone Colore unico Grigio', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (30, 28, 325, 'M', 'Giacca a vento con cappuccio e zip mimetico', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (31, 29, 325, 'M', 'Giacca a vento con tasca e patta gialla', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (32, 34, 325, 'M', 'Giacca a vento con zip color block', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (33, 43, 325, 'M', 'Giacca a vento da uomo con bottoni', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (34, 21, 325, 'M', 'Giacca bomber con grafica di lettere senza maglietta', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (35, 22, 325, 'M', 'Giacca bomber con ricamo lettera', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (36, 22, 325, 'M', 'Giacca bomber con ricamo lettera', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (37, 22, 325, 'M', 'Giacca bomber con ricamo lettera', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (38, 22, 325, 'M', 'Giacca bomber con stampa mimetica', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (39, 21, 325, 'M', 'Giacca bomber con zip', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (40, 24, 325, 'M', 'Giacca con cappuccio e coulisse con zip color black', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (41, 43, 325, 'M', 'Giacca da ciclisimo con collo a bavero in PU', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (42, 59, 325, 'M', 'Giacca da moto in pelle PU con cerniera frontale da uomo', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (43, 28, 325, 'M', 'Giacca da uomo con cappuccio e zip con coulisse', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (44, 28, 325, 'M', 'Giacca da uomo con cappuccio e zip con coulisse', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (45, 37, 325, 'M', 'Giacca da uomo in cotone con cappuccio, tasca laterale con cerniera e dettaglio in fettuccia', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (46, 24, 325, 'M', 'Giacca mimetica con zip', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (47, 44, 325, 'M', 'Giacca piumino con toppa', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (48, 9, 325, 'M', 'Costume da bagno con coulisse con stampa tropicale', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (49, 15, 325, 'M', 'Costume da bagno con coulisse con tasca con zip', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (50, 15, 325, 'M', 'Costume da bagno con coulisse con tasca con zip', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (51, 15, 325, 'M', 'Costume da bagno con coulisse con tasca con zip', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (52, 15, 325, 'M', 'Costume da bagno con coulisse con tasca con zip', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (53, 12, 325, 'M', 'Costume da bagno con coulisse in vita grafica con lettera blu', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (54, 12, 325, 'M', 'Costume da bagno con coulisse in vita grafica con lettera', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (55, 12, 325, 'M', 'Costume da bagno con coulisse in vita grafica con lettera', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (56, 9, 325, 'M', 'Costume da bagno da uomo con coulisse e stampa albero di palma', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (57, 14, 325, 'M', 'Costume da bagno da uomo con stampa fenicottero', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (58, 14, 325, 'M', 'Costume da bagno da uomo con stampa fenicottero', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (59, 8, 325, 'M', 'Costumi da uomo Animale Vacanza', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (60, 14, 325, 'M', 'Costumi da uomo Cordone Fenicottero Vacanza', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (61, 8, 325, 'M', 'Costumi da uomo Cordone stampa dappertutto Vacanza', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (62, 8, 325, 'M', 'Costumi da uomo Cordone Tropicale Vacanza', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (63, 14, 325, 'M', 'Costumi da uomo Creste Lettere Vacanza', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (64, 15, 325, 'M', 'Shorts a righe da spiaggia da uomo con coulisse', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (65, 12, 325, 'M', 'Shorts da bagno con coulisse a righe', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (66, 14, 325, 'M', 'Shorts da spiaggia stampato con coulisse da uomo', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (67, 11, 325, 'M', 'Trunks da nuoto a righe ananas', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (68, 15, 325, 'M', 'Trunks da nuoto con coulisse grafica fumetto', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (69, 15, 325, 'M', 'Trunks da nuoto con coulisse ombre da uomo', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (70, 15, 325, 'M', 'Trunks da nuoto con coulisse ombre da uomo', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (71, 15, 325, 'M', 'Trunks da nuoto con coulisse ombre da uomo', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (72, 15, 325, 'M', 'Trunks da nuoto con tasca e coulisse', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (73, 15, 325, 'M', 'Trunks da nuoto con tasca e coulisse', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (74, 15, 325, 'M', 'Trunks da nuoto con tasca e coulisse', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (75, 15, 325, 'M', 'Trunks da nuoto con tasca e coulisse', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (76, 15, 325, 'M', 'Trunks da nuoto con tasca e coulisse', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (77, 11, 325, 'M', 'Trunks da nuoto stampato', 0, 3);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (78, 17, 325, 'M', 'Felpa con cappuccio con coulisse e stampa fulmine da uomo', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (79, 20, 325, 'M', 'Felpa con cappuccio e coulisse con stampa lettera da uomo', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (80, 17, 325, 'M', 'Felpa con cappuccio e coulisse grafica lettera', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (81, 15, 325, 'M', 'Felpa con cappuccio e manica raglan e fascia neon e fumetto grafico da uomo', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (82, 18, 325, 'M', 'Felpa con cappuccio e slogan grafico', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (83, 19, 325, 'M', 'Felpa con cappuccio e tasca con stampa floreale e giapponese', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (84, 19, 325, 'M', 'Felpa con cappuccio e tasca con stampa floreale e giapponese', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (85, 15, 325, 'M', 'Felpa con stampa drago e lettera cinese', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (86, 15, 325, 'M', 'Felpa con stampa floreale e slogan da uomo', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (87, 18, 325, 'M', 'Felpa con stampa mano da uomo', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (88, 20, 325, 'M', 'Felpe da uomo Cordone Floreale Strada', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (89, 20, 325, 'M', 'Felpe da uomo Cordone Floreale Strada', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (90, 20, 325, 'M', 'Felpe da uomo Cordone Floreale Strada', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (91, 18, 325, 'M', 'Felpe da uomo Cordone Grafico Strada', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (92, 18, 325, 'M', 'Felpe da uomo Cordone Grafico Strada', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (93, 24, 325, 'M', 'Felpe da uomo Cordone Lettere College', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (94, 22, 325, 'M', 'Felpe da uomo Cordone Lettere Strada', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (95, 20, 325, 'M', 'Felpe da uomo Cordone slogan College', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (96, 17, 325, 'M', 'Felpe da uomo Grafico Strada', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (97, 14, 325, 'M', 'Felpe da uomo Lettere Casual', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (98, 20, 325, 'M', 'Felpe da uomo Ricamo quadri College', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (99, 15, 325, 'M', 'Felpa con cappuccio e coulisse grafica fumetto', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (100, 15, 325, 'M', 'Felpa con cappuccio e coulisse grafica fumetto', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (101, 15, 325, 'M', 'Felpa con cappuccio e coulisse grafica fumetto', 0, 6);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (102, 22, 325, 'M', 'Shorts da pista monocolore con vita con coulisse', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (103, 12, 325, 'M', 'Shorts da pista monocolore con vita con coulisse', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (104, 10, 325, 'M', 'Pantaloncini da uomo Cordone Fuoco Multicolore Strada', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (105, 18, 325, 'M', 'Pantaloncini da uomo Cordone Grafico nero Casual', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (106, 10, 325, 'M', 'Pantaloncini da uomo Cordone Lettere Casual NASA', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (107, 12, 325, 'M', 'Pantaloncini da uomo militare', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (108, 15, 325, 'M', 'Pantaloncini da uomo Tasca quadri Casual', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (109, 9, 325, 'M', 'Pantaloncini da uomo Tasca slogan Casual', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (110, 11, 325, 'M', 'Pantaloncini da uomo Tasca slogan Casual', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (111, 15, 325, 'M', 'Shorts bermuda con fasce e patta laterale', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (112, 16, 325, 'M', 'Shorts con coulisse in vita con tasca e patta laterale', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (113, 14, 325, 'M', 'Shorts con coulisse in vita con tasca e patta laterale', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (114, 10, 325, 'M', 'Shorts da uomo con vita elastica e stampa grafica', 0, 12);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (115, 23, 325, 'M', 'Pantaloni a quadri con orlo con coulisse', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (116, 15, 325, 'M', 'Pantaloni a righe con coulisse in vita', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (117, 17, 325, 'M', 'Pantaloni cargo con tasca con patta con grafica di lettere', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (118, 27, 325, 'M', 'Pantaloni cargo con tasca con patta con grafica di lettere', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (119, 22, 325, 'M', 'Pantaloni cargo con tasca e stampa mimetico', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (120, 16, 325, 'M', 'Pantaloni cargo con tasca e stampa mimetico', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (121, 17, 325, 'M', 'Pantaloni cargo con tasca e stampa mimetico', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (122, 23, 325, 'M', 'Pantaloni con stampa fulmine da uomo', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (123, 18, 325, 'M', 'Pantaloni con stampa fulmine da uomo', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (124, 15, 325, 'M', 'Pantaloni con tasca inclinata grafica con lettera', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (125, 26, 325, 'M', 'Pantaloni con toppa stella con fibbia', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (126, 21, 325, 'M', 'Pantaloni con toppa stella con fibbia', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (127, 24, 325, 'M', 'Pantaloni da uomo Cordone Colore unico Casual', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (128, 19, 325, 'M', 'Pantaloni da uomo Tasca Lettere nero Strada', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (129, 18, 325, 'M', 'Pantaloni di carota con coulisse in vita cachi', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (130, 24, 325, 'M', 'Pantaloni pantofole con pannello a contrasto', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (131, 22, 325, 'M', 'Pantaloni sportivi con stampa di slogan e grafica', 0, 11);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (132, 14, 325, 'M', 'Polo da uomo Bottoni A strisce Blu Navy Ufficio', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (133, 12, 325, 'M', 'Polo comoda monocolore', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (134, 12, 325, 'M', 'Camicia polo da uomo con bordo a contrasto e ricamo', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (135, 13, 325, 'M', 'Camicia polo con bordo a contrasto da uomo', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (136, 12, 325, 'M', 'Camicia polo da uomo con stampa giraffa & a righe', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (137, 15, 325, 'M', 'Camicia polo da uomo con collo dritto e bottone mezzo', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (138, 15, 325, 'M', 'Camicia polo da uomo con collo dritto e bottone mezzo', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (139, 15, 325, 'M', 'Camicia polo da uomo con collo dritto e bottone mezzo', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (140, 15, 325, 'M', 'Camicia polo da uomo con collo dritto e bottone mezzo', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (141, 15, 325, 'M', 'Maglietta con bottone un quarto con pannello a contrasto', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (142, 14, 325, 'M', 'Camicia polo con ricamo lettera', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (143, 14, 325, 'M', 'Camicia polo con ricamo lettera', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (144, 14, 325, 'M', 'Camicia polo a quadri in contrasto da uomo', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (145, 14, 325, 'M', 'Camicia polo a quadri in contrasto da uomo', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (146, 15, 325, 'M', 'Camicia polo da uomo con bordo a righe a contrasto', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (147, 15, 325, 'M', 'Camicia polo da uomo con bordo a righe a contrasto', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (148, 14, 325, 'M', 'Camicia polo con ricamo e collo a contrasto', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (149, 15, 325, 'M', 'Camicia polo con stampa foglia e collo a contrasto', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (150, 13, 325, 'M', 'Camicia polo con blocchi di colore da uomo', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (151, 13, 325, 'M', 'Camicia polo con blocchi di colore da uomo', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (152, 13, 325, 'M', 'Polo con orlo a righe', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (153, 13, 325, 'M', 'Polo con orlo a righe', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (154, 13, 325, 'M', 'Polo con orlo a righe', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (155, 13, 325, 'M', 'Polo con orlo a righe', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (156, 15, 325, 'M', 'Polo da uomo Bottoni A strisce Casual', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (157, 14, 325, 'M', 'Polo da uomo Bottone frontale Blocchi di colore Casual', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (158, 14, 325, 'M', 'Polo con nastro a righe', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (159, 13, 325, 'M', 'Polo da uomo Bordo a contrasto Blu Navy Ufficio', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (160, 11, 325, 'M', 'Camicia polo monocolore', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (161, 11, 325, 'M', 'Camicia polo monocolore', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (162, 11, 325, 'M', 'Camicia polo monocolore', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (163, 10, 325, 'M', 'Camicia polo con manica corta', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (164, 14, 325, 'M', 'Maglietta polo con collo a contrasto', 0, 8);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (165, 13, 325, 'M', 'Camicia monocolore con spalle cadenti', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (166, 14, 325, 'M', 'Camicia a quadri', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (167, 14, 325, 'M', 'Camicia a quadri', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (168, 14, 325, 'M', 'Camicia con bottone con tasca frontale', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (169, 14, 325, 'M', 'Camicia con bottone con tasca frontale', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (170, 16, 325, 'M', 'Camicia a catena e cranio con bottone da uomo', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (171, 13, 325, 'M', 'Camicia con bottone frontale con stampa di patchwork', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (172, 14, 325, 'M', 'Camicie da uomo Bordo a contrasto College', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (173, 10, 325, 'M', 'Kimono con stampa di graffiti', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (174, 19, 325, 'M', 'Camicia a quadri in flanella con bottone', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (175, 19, 325, 'M', 'Camicia a quadri in flanella con bottone', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (176, 19, 325, 'M', 'Camicia a quadri in flanella con bottone', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (177, 10, 325, 'M', 'Kimono con stampa drago cinese', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (178, 19, 325, 'M', 'Camicie da uomo Tasca Colore unico Casual', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (179, 19, 325, 'M', 'Camicie da uomo Tasca Colore unico Casual', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (180, 15, 325, 'M', 'Kimono da uomo con stampa halloween', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (181, 15, 325, 'M', 'Kimono da uomo con stampa halloween', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (182, 13, 325, 'M', 'Camicia con bottone e stamap paisley', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (183, 13, 325, 'M', 'Camicia con bottone e stamap paisley', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (184, 11, 325, 'M', 'Camicia con fiamme', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (185, 15, 325, 'M', 'Camicie da uomo Bottone frontale Macchia di colore Vacanza', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (186, 12, 325, 'M', 'Camicia stampa draghi', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (187, 12, 325, 'M', 'Camicia stampa draghi', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (188, 18, 325, 'M', 'Camicie da uomo Bottone frontale Colore unico', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (189, 18, 325, 'M', 'Camicie da uomo Bottone frontale Colore unico', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (190, 18, 325, 'M', 'Camicie da uomo Bottone frontale Colore unico', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (191, 14, 325, 'M', 'Camicia con toppa con collo a revere', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (192, 14, 325, 'M', 'Camicia con toppa con collo a revere', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (193, 13, 325, 'M', 'Camicia con bottone con stampa paisley', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (194, 11, 325, 'M', 'Kimono bicolore con spalle cadenti', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (195, 15, 325, 'M', 'Camicie da uomo Animale Strada', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (196, 11, 325, 'M', 'Camicia a righe', 0, 7);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (197, 9, 325, 'M', 'Maglietta cest la vie', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (198, 8, 325, 'M', 'Maglietta farfalla', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (199, 8, 325, 'M', 'Maglietta alieni', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (200, 10, 325, 'M', 'Maglietta con stampa creato', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (201, 10, 325, 'M', 'Maglietta con stampa creato', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (202, 11, 325, 'M', 'Maglietta stampa scritte', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (203, 12, 325, 'M', 'Maglietta stampa occhi', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (204, 12, 325, 'M', 'Maglietta stampa occhi', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (205, 12, 325, 'M', 'Maglietta stampa occhi', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (206, 11, 325, 'M', 'Maglietta con lacci', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (207, 10, 325, 'M', 'Maglietta con fulmini', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (208, 9, 325, 'M', 'Maglietta stampa tsunami', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (209, 9, 325, 'M', 'Maglietta stampa tsunami', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (210, 9, 325, 'M', 'Maglietta stampa tsunami', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (211, 18, 325, 'M', 'Magliette x2', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (212, 18, 325, 'M', 'Magliette x2', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (213, 18, 325, 'M', 'Magliette x2', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (214, 11, 325, 'M', 'Maglietta con stampe e scritte', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (215, 11, 325, 'M', 'Maglietta con stampe e scritte', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (216, 8, 325, 'M', 'Maglietta foresta', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (217, 9, 325, 'M', 'Maglietta con stampe', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (218, 7, 325, 'M', 'Maglietta be nice', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (219, 7, 325, 'M', 'Maglietta be nice', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (220, 7, 325, 'M', 'Maglietta be nice', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (221, 9, 325, 'M', 'Maglietta stampe giapponesi', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (222, 9, 325, 'M', 'Maglietta stampe giapponesi', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (223, 11, 325, 'M', 'Maglietta con rosa', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (224, 11, 325, 'M', 'Maglietta con rosa', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (225, 11, 325, 'M', 'Maglietta con rosa', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (226, 12, 325, 'M', 'Maglietta con drago', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (227, 13, 325, 'M', 'Maglietta week', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (228, 13, 325, 'M', 'Maglietta week', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (229, 8, 325, 'M', 'Maglietta mappa', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (230, 8, 325, 'M', 'Maglietta mappa', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (231, 8, 325, 'M', 'Maglietta mappa', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (232, 13, 325, 'M', 'Maglietta palme', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (233, 11, 325, 'M', 'Maglietta a righe', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (234, 11, 325, 'M', 'Maglietta a righe', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (235, 11, 325, 'M', 'Maglietta a righe', 0, 9);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (236, 27, 325, 'F', 'Cappotti Tasca Colore unico Casual ', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (237, 27, 325, 'F', 'Cappotti Tasca Colore unico Casual', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (238, 27, 325, 'F', 'Cappotti Tasca Colore unico Casual', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (239, 27, 325, 'F', 'Cappotti Tasca Colore unico Casual', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (240, 20, 325, 'F', 'Cappotto a quadri con spalle cadenti e orlo curvo', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (241, 27, 325, 'F', 'Cappotto a quadri con tasca e orlo curvo', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (242, 27, 325, 'F', 'Cappotto a quadri con tasca e orlo curvo', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (243, 27, 325, 'F', 'Cappotto a quadri con tasca e orlo curvo', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (244, 9, 325, 'F', 'Cappotto aperto frontale con dettaglio tasca', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (245, 16, 325, 'F', 'Cappotto con cappuccio con bottone e coulisse', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (246, 16, 325, 'F', 'Cappotto con cappuccio con bottone e coulisse', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (247, 26, 325, 'F', 'Cappotto con colletto a revers con monopetto ', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (248, 26, 325, 'F', 'Cappotto con colletto a revers con monopetto ', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (249, 19, 325, 'F', 'Cappotto con spalle cadenti e bottone a quadri ', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (250, 19, 325, 'F', 'Cappotto con spalle cadenti e bottone a quadri ', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (251, 19, 325, 'F', 'Cappotto con spalle cadenti e bottone a quadri ', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (252, 21, 325, 'F', 'Cappotto con tasca e collo a scialle ', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (253, 21, 325, 'F', 'Cappotto con tasca e collo a scialle ', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (254, 21, 325, 'F', 'Cappotto con tasca e collo a scialle ', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (255, 21, 325, 'F', 'Cappotto con tasca e collo a scialle ', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (256, 17, 325, 'F', 'Cappotto con tasca sul lato e doppio petto', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (257, 17, 325, 'F', 'Cappotto con tasca sul lato e doppio petto', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (258, 22, 325, 'F', 'Cappotto in pelle PU con tasca e monopetto', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (259, 19, 325, 'F', 'Cappotto monocolore con spalle cadenti e bottone', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (260, 19, 325, 'F', 'Cappotto monocolore con spalle cadenti e bottone', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (261, 20, 325, 'F', 'Cappotto pea con collo a bavero e doppio petto', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (262, 20, 325, 'F', 'Cappotto pea con collo a bavero e doppio petto', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (263, 20, 325, 'F', 'Cappotto pea con collo a bavero e doppio petto', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (264, 25, 325, 'F', 'Cappotto trench con cinture e doppio petto', 0, 1);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (265, 16, 325, 'F', 'Giacca a vento con cappuccio e coulisse con zip ', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (266, 13, 325, 'F', 'Giacca a vento con cappuccio riflessivo e zipper up', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (267, 9, 325, 'F', 'Giacca bomber con zip e stampa floreale', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (268, 9, 325, 'F', 'Giacca bomber con zip e stampa floreale', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (269, 12, 325, 'F', 'Giacca bomber monocolore con dettaglio cerniera', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (270, 12, 325, 'F', 'Giacca bomber monocolore con dettaglio cerniera', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (271, 12, 325, 'F', 'Giacca bomber monocolore con dettaglio cerniera', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (272, 20, 325, 'F', 'Giacca con cappuccio con coulisse con tasca frontale con zip', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (273, 14, 325, 'F', 'Giacca con cappuccio e coulisse e zipper up', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (274, 14, 325, 'F', 'Giacca con cappuccio e coulisse e zipper up', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (275, 14, 325, 'F', 'Giacca con cappuccio e coulisse e zipper up', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (276, 34, 325, 'F', 'Giacca da ciclisimo in PU con zip e collo a bavero', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (277, 15, 325, 'F', 'Giacca in PU con monopetto', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (278, 17, 325, 'F', 'Giacca riflessivo con zip color block', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (279, 20, 325, 'F', 'Giacche Bottone frontale Blocchi di colore Sportivo', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (280, 17, 325, 'F', 'Giacche Bottone frontale Lettere Sportivo', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (281, 29, 325, 'F', 'Giacche Cerniera Colore unico Casual', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (282, 29, 325, 'F', 'Giacche Cerniera Colore unico Casual', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (283, 29, 325, 'F', 'Giacche Cerniera Colore unico Casual', 0, 2);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (284, 11, 325, 'F', 'Bikini mutandine con stampa palma e top con cinturino regolabile ', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (285, 11, 325, 'F', 'Bikini mutandine con stampa palma e top con cinturino regolabile ', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (286, 11, 325, 'F', 'Costume da bagno bikini bicolore con taglio alto', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (287, 11, 325, 'F', 'Costume da bagno bikini bicolore con taglio alto', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (288, 10, 325, 'F', 'Costume da bagno bikini con stampa foglia ', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (289, 10, 325, 'F', 'Costume da bagno bikini con stampa foglia ', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (290, 10, 325, 'F', 'Costume da bagno bikini con stampa foglia ', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (291, 10, 325, 'F', 'Costume da bagno bikini con taglio alto', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (292, 13, 325, 'F', 'Costume da bagno bikini con vita alta e nodo di blocchi di colore', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (293, 13, 325, 'F', 'Costume da bagno bikini con vita alta e nodo di blocchi di colore', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (294, 11, 325, 'F', 'Costume da bagno bikini nodo laterale incrociato leopardo', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (295, 10, 325, 'F', 'Costume da bagno bikini semplice', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (296, 11, 325, 'F', 'Costume da bagno monocolore con cut alto', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (297, 12, 325, 'F', 'Set bibkini top triangolo in raso e perizoma', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (298, 10, 325, 'F', 'Set bikini top halter con lacci e nodo laterale', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (299, 10, 325, 'F', 'Set bikini top halter con lacci e nodo laterale', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (300, 10, 325, 'F', 'Set bikini top halter con lacci e nodo laterale', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (301, 11, 325, 'F', 'Sets bikini Colore unico', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (302, 11, 325, 'F', 'Sets bikini Colore unico', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (303, 11, 325, 'F', 'Sets bikini Colore unico', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (304, 11, 325, 'F', 'Sets bikini Spalline incrociate Colore unico', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (305, 12, 325, 'F', 'Sets bikini Tie Dye Sexy', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (306, 12, 325, 'F', 'Sets bikini Tie Dye Sexy', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (307, 10, 325, 'F', 'Sets bikini Torsate Colore unico Carino', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (308, 10, 325, 'F', 'Sets bikini Torsate Colore unico Carino', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (309, 10, 325, 'F', 'Sets bikini Torsate Colore unico Carino', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (310, 10, 325, 'F', 'Sets bikini Torsate Colore unico Carino', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (311, 10, 325, 'F', 'Sets bikini Torsate Colore unico Carino', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (312, 12, 325, 'F', 'Sets bikini Torsate Tropicale Sexy', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (313, 11, 325, 'F', 'Sets bikini Volanti Colore unico Carino', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (314, 11, 325, 'F', 'Sets bikini Volanti Colore unico Carino', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (315, 10, 325, 'F', 'Sets bikini Volanti Colore unico Sexy', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (316, 10, 325, 'F', 'Sets bikini Volanti Colore unico Sexy', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (317, 10, 325, 'F', 'Sets bikini Volanti Colore unico Sexy', 0, 4);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (318, 12, 325, 'F', 'Costume da bagno a croce con rete', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (319, 12, 325, 'F', 'Costume da bagno bicolore con monospalle', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (320, 12, 325, 'F', 'Costume da bagno bicolore con monospalle', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (321, 12, 325, 'F', 'Costume da bagno bicolore con monospalle', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (322, 12, 325, 'F', 'Costume da bagno bicolore con monospalle', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (323, 12, 325, 'F', 'Costume da bagno intero bandeau in tulle a contrasto', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (324, 12, 325, 'F', 'Costume da bagno intero con capestro e collo profondo e stampa tropicale', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (325, 13, 325, 'F', 'Costume da bagno intero con orlo arricciato', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (326, 12, 325, 'F', 'Costume da bagno intero con taglio ', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (327, 12, 325, 'F', 'Costume da bagno intero con taglio ', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (328, 12, 325, 'F', 'Costume da bagno intero con taglio ', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (329, 11, 325, 'F', 'Costume da bagno intero floreale con appliques', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (330, 13, 325, 'F', 'Costume da bagno intero halter plissettato', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (331, 13, 325, 'F', 'Costume da bagno intero halter plissettato', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (332, 13, 325, 'F', 'Costume da bagno intero halter plissettato', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (333, 14, 325, 'F', 'Costume da bagno intero incrociato con nodo frontale', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (334, 14, 325, 'F', 'Costume da bagno intero incrociato con nodo frontale', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (335, 11, 325, 'F', 'Intero Spalline incrociate Colore unico Casual', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (336, 11, 325, 'F', 'Intero Spalline incrociate Colore unico Casual', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (337, 12, 325, 'F', 'Monokini tropicale halter incrociato con cut out in vita', 0, 5);
INSERT INTO articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (338, 12, 325, 'F', 'Tuta con cut out effetto serpente', 0, 5);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (339, 14, 325, 'F', 'Felpa a quadri a contrasto con cappuccio e coulisse e tasca di canguro frontale', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (340, 17, 325, 'F', 'Felpa con cappuccio colorblock con tasca a marsupio stampa luna e sole', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (341, 13, 325, 'F', 'Felpa con cappuccio con coulisse e manica raglan', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (342, 15, 325, 'F', 'Felpa con cappuccio di blocchi di colore con coulisse e spalle cadenti', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (343, 14, 325, 'F', 'Felpa con cappuccio e coulisse con spalle cadenti e orlo curvo', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (344, 15, 325, 'F', 'Felpa con cappuccio e coulisse e zip', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (345, 15, 325, 'F', 'Felpa con cappuccio e coulisse e zip', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (346, 15, 325, 'F', 'Felpa con cappuccio e coulisse e zip', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (347, 12, 325, 'F', 'Felpa con cappuccio e coulisse e zipper-up e fasce sul lato', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (348, 15, 325, 'F', 'Felpa con cappuccio e zipper up e coulisse e stampa a righe', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (349, 9, 325, 'F', 'Felpa con cappuccio foderata termica monocolore con coulisse', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (350, 9, 325, 'F', 'Felpa con cappuccio foderata termica monocolore con coulisse', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (351, 9, 325, 'F', 'Felpa con cappuccio foderata termica monocolore con coulisse', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (352, 9, 325, 'F', 'Felpa con cappuccio foderata termica monocolore con coulisse', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (353, 9, 325, 'F', 'Felpa con cappuccio foderata termica monocolore con coulisse', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (354, 14, 325, 'F', 'Felpa con cappuccio larga con coulisse e lettera grafica e tasca a canguro', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (355, 14, 325, 'F', 'Felpa con cappuccio larga con coulisse e lettera grafica e tasca a canguro', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (356, 11, 325, 'F', 'Felpa con collo asimmetrico e nastro di stampa lettera & corona', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (357, 12, 325, 'F', 'Felpa con grafica di lettere', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (358, 12, 325, 'F', 'Felpa con grafica di lettere', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (359, 12, 325, 'F', 'Felpa con grafica di lettere', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (360, 15, 325, 'F', 'Felpa con spalle cadenti grafica lettera', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (361, 15, 325, 'F', 'Felpa con spalle cadenti grafica lettera', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (362, 12, 325, 'F', 'Felpa corta con cappuccio e maniche a scritte', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (363, 21, 325, 'F', 'Felpa crop con cappuccio e coulisse con zip e tasca', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (364, 21, 325, 'F', 'Felpa crop con cappuccio e coulisse con zip e tasca', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (365, 21, 325, 'F', 'Felpa crop con cappuccio e coulisse con zip e tasca', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (366, 21, 325, 'F', 'Felpa crop con cappuccio e coulisse con zip e tasca', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (367, 14, 325, 'F', 'Felpe Cerniera Colore unico Casual', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (368, 14, 325, 'F', 'Felpe Cerniera Colore unico Casual', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (369, 16, 325, 'F', 'Felpe Cerniera Colore unico Casual', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (370, 15, 325, 'F', 'Felpe Cordone Animale Casual', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (371, 15, 325, 'F', 'Felpe Cordone Blocchi di colore Casual', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (372, 12, 325, 'F', 'Felpe Cordone Colore unico Casual', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (373, 12, 325, 'F', 'Felpe Cordone Colore unico Casual', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (374, 12, 325, 'F', 'Felpe Cordone Colore unico Casual', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (375, 12, 325, 'F', 'Felpe Cordone Lettere Casual ', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (376, 13, 325, 'F', 'Felpe Lettere Casual', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (377, 12, 325, 'F', 'Pullover oversized con spalle cadenti e nastro arcobaleno', 0, 6);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (378, 8, 325, 'F', 'Gonna a pied de poule e cerniera', 0, 13);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (379, 8, 325, 'F', 'Gonna a pied de poule e cerniera', 0, 13);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (380, 8, 325, 'F', 'Gonna a pied de poule e cerniera', 0, 13);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (381, 9, 325, 'F', 'Gonna aderente', 0, 13);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (382, 11, 325, 'F', 'Gonna chiffon floreale con orlo arricciato con vita elasticizzata', 0, 13);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (383, 13, 325, 'F', 'Gonna con bottone frontale ', 0, 13);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (384, 13, 325, 'F', 'Gonna con bottone frontale ', 0, 13);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (385, 13, 325, 'F', 'Gonna con bottone frontale ', 0, 13);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (386, 11, 325, 'F', 'Gonna dritta con frange', 0, 13);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (387, 14, 325, 'F', 'Gonna Incrociata asimmetrica a volant', 0, 13);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (388, 15, 325, 'F', 'Gonna jacquard a fessura con bottone', 0, 13);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (389, 12, 325, 'F', 'Gonna margherita ', 0, 13);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (390, 14, 325, 'F', 'Gonna Nodo', 0, 13);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (391, 14, 325, 'F', 'Gonna Nodo', 0, 13);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (392, 14, 325, 'F', 'Gonna Nodo', 0, 13);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (393, 15, 325, 'F', 'Gonna Nodo Elegante', 0, 13);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (394, 11, 325, 'F', 'Gonna plissettata a quadri', 0, 13);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (395, 8, 325, 'F', 'Gonna plissettata', 0, 13);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (396, 9, 325, 'F', 'Gonna plissettata in raso', 0, 13);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (397, 11, 325, 'F', 'Gonna plissettata mini a quadri multicolore', 0, 13);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (398, 10, 325, 'F', 'Gonna plissettata', 0, 13);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (399, 12, 325, 'F', 'Gonna lucida', 0, 13);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (400, 13, 325, 'F', 'Gonne Orlo arricciato stampa dappertutto Casual', 0, 13);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (401, 13, 325, 'F', 'Gonna con fessura e vita alta', 0, 14);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (402, 13, 325, 'F', 'Gonna con fessura e vita alta', 0, 14);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (403, 13, 325, 'F', 'Gonna con fessura e vita alta', 0, 14);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (404, 13, 325, 'F', 'Gonna con fessura e vita alta', 0, 14);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (405, 15, 325, 'F', 'Gonna con orlo arricciato con margherita', 0, 14);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (406, 16, 325, 'F', 'Gonna con spacchi a coscia con stampa geo', 0, 14);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (407, 17, 325, 'F', 'Gonna con stampa', 0, 14);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (408, 14, 325, 'F', 'Gonna floreale con orlo arricciato', 0, 14);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (409, 16, 325, 'F', 'Gonna floreale plissettato pieghe', 0, 14);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (410, 17, 325, 'F', 'Gonna lunga plissettata ombre', 0, 14);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (411, 14, 325, 'F', 'Gonna monocolore con bottone', 0, 14);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (412, 13, 325, 'F', 'Gonna plissettata con cintura larga', 0, 14);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (413, 13, 325, 'F', 'Gonna plissettata con stampa di tigre', 0, 14);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (414, 13, 325, 'F', 'Camicetta bicolore con bottone', 0, 7);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (415, 13, 325, 'F', 'Camicetta con bottone e tasca monocolore', 0, 7);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (416, 15, 325, 'F', 'Camicetta con bottone frontale con stampa di cuore', 0, 7);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (417, 14, 325, 'F', 'Camicetta corta con bottone', 0, 7);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (418, 14, 325, 'F', 'Camicetta corta con bottone', 0, 7);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (419, 16, 325, 'F', 'Camicetta di tweed corte con bottone', 0, 7);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (420, 12, 325, 'F', 'Camicetta floreale', 0, 7);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (421, 10, 325, 'F', 'Camicetta monocolore con bordo in pizzo', 0, 7);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (422, 10, 325, 'F', 'Camicetta monocolore con bordo in pizzo', 0, 7);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (423, 9, 325, 'F', 'Camicetta monocolore con bottone', 0, 7);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (424, 14, 325, 'F', 'Camicie Schiena scoperta A strisce Bohemien', 0, 7);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (425, 8, 325, 'F', 'Camicie Volanti Cuore Casual', 0, 7);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (426, 8, 325, 'F', 'Camicie Volanti Cuore Casual', 0, 7);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (427, 8, 325, 'F', 'Camicie Volanti Cuore Casual', 0, 7);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (428, 8, 325, 'F', 'Top a pois annodato arricciato con volant ', 0, 7);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (429, 8, 325, 'F', 'Top a pois annodato arricciato con volant ', 0, 7);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (430, 8, 325, 'F', 'Top a pois annodato arricciato con volant ', 0, 7);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (431, 8, 325, 'F', 'Top a pois annodato arricciato con volant ', 0, 7);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (432, 11, 325, 'F', 'Maglietta a croce con nodo', 0, 9);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (433, 12, 325, 'F', 'Maglietta con lettera e auto grafici', 0, 9);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (434, 12, 325, 'F', 'Maglietta con lettera e auto grafici', 0, 9);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (435, 12, 325, 'F', 'Maglietta con lettera e auto grafici', 0, 9);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (436, 12, 325, 'F', 'Maglietta con lettera e auto grafici', 0, 9);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (437, 9, 325, 'F', 'Maglietta con stampa piuma colorata', 0, 9);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (438, 8, 325, 'F', 'Maglietta con stampa vino & ECG', 0, 9);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (439, 8, 325, 'F', 'Maglietta con stampa vino & ECG', 0, 9);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (440, 11, 325, 'F', 'Maglietta corta incrociata', 0, 9);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (441, 12, 325, 'F', 'Maglietta free hugs', 0, 9);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (442, 11, 325, 'F', 'Maglietta girasole', 0, 9);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (443, 10, 325, 'F', 'Maglietta grafica lettera e dente di leone', 0, 9);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (444, 10, 325, 'F', 'Maglietta grafica lettera e dente di leone', 0, 9);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (445, 15, 325, 'F', 'Maglietta nasa', 0, 9);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (446, 15, 325, 'F', 'Maglietta nera oversized con spalle cadenti con stampa di occhi', 0, 9);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (447, 13, 325, 'F', 'Maglietta oversize con spalle cadenti grafica lettera ', 0, 9);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (448, 13, 325, 'F', 'Maglietta oversize con spalle cadenti grafica lettera ', 0, 9);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (449, 13, 325, 'F', 'Maglietta oversize con spalle cadenti grafica lettera ', 0, 9);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (450, 9, 325, 'F', 'Maglietta stampata', 0, 9);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (451, 9, 325, 'F', 'Maglietta stampata', 0, 9);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (452, 10, 325, 'F', 'Taglia la tuta di scollo rotonda del neckline di V', 0, 9);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (453, 7, 325, 'F', 'Top a costine con bretelle sottile a righe', 0, 10);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (454, 8, 325, 'F', 'Top a righe con stampa cuore', 0, 10);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (455, 8, 325, 'F', 'Top a righe con stampa cuore', 0, 10);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (456, 8, 325, 'F', 'Top a righe con stampa cuore', 0, 10);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (457, 12, 325, 'F', 'Top con capestro e nodo monocolore', 0, 10);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (458, 12, 325, 'F', 'Top con capestro e nodo monocolore', 0, 10);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (459, 12, 325, 'F', 'Top con capestro e nodo monocolore', 0, 10);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (460, 11, 325, 'F', 'Top corto con orlo a smerlo con pizzo', 0, 10);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (461, 11, 325, 'F', 'Top corto con orlo a smerlo con pizzo', 0, 10);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (462, 6, 325, 'F', 'Top crop con bretelle sottile a costine', 0, 10);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (463, 6, 325, 'F', 'Top crop con bretelle sottile a costine', 0, 10);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (464, 6, 325, 'F', 'Top crop con bretelle sottile a costine', 0, 10);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (465, 6, 325, 'F', 'Top crop con bretelle sottile a costine', 0, 10);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (466, 9, 325, 'F', 'Top in raso con bretelle sottile con lacci', 0, 10);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (467, 9, 325, 'F', 'Top in raso con bretelle sottile con lacci', 0, 10);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (468, 9, 325, 'F', 'Top in raso con bretelle sottile con lacci', 0, 10);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (469, 19, 325, 'F', '3 pezzi shorts con coulisse', 0, 12);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (470, 10, 325, 'F', 'Shorts ampi a pois con cinture', 0, 12);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (471, 10, 325, 'F', 'Shorts ampi a pois con cinture', 0, 12);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (472, 16, 325, 'F', 'Shorts ampi con doppio petto', 0, 12);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (473, 11, 325, 'F', 'Shorts bermuda con sligan grafico', 0, 12);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (474, 11, 325, 'F', 'Shorts Bottoni Colore unico Elegante', 0, 12);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (475, 11, 325, 'F', 'Shorts Bottoni Colore unico Elegante', 0, 12);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (476, 11, 325, 'F', 'Shorts Bottoni Colore unico Elegante', 0, 12);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (477, 8, 325, 'F', 'Shorts culotte con zip', 0, 12);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (478, 16, 325, 'F', 'Shorts in PU con cinture e fibbia con orlo arrotolato', 0, 12);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (479, 16, 325, 'F', 'Shorts larghi tweed monocolore', 0, 12);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (480, 8, 325, 'F', 'Shorts Lettere Casual', 0, 12);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (481, 8, 325, 'F', 'Shorts monocolore con cintura e vita a volant sovrapposti', 0, 12);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (482, 8, 325, 'F', 'Shorts monocolore con cintura e vita a volant sovrapposti', 0, 12);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (483, 8, 325, 'F', 'Shorts monocolore con cintura e vita a volant sovrapposti', 0, 12);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (484, 9, 325, 'F', 'Shorts Volanti Colore unico Casual', 0, 12);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (485, 9, 325, 'F', 'Shorts Volanti Colore unico Casual', 0, 12);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (486, 7, 325, 'F', 'Leggins monocolori con vita alta elastica', 0, 11);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (487, 10, 325, 'F', 'Pantaloni a zampa con nodo indietro', 0, 11);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (488, 10, 325, 'F', 'Pantaloni a zampa con nodo indietro', 0, 11);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (489, 10, 325, 'F', 'Pantaloni a zampa con nodo indietro', 0, 11);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (490, 14, 325, 'F', 'Pantaloni Animale Casual', 0, 11);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (491, 13, 325, 'F', 'Pantaloni Cerniera Floreale Bohemien', 0, 11);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (492, 14, 325, 'F', 'Pantaloni della tuta con tasca inclinata e vita elastica', 0, 11);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (493, 14, 325, 'F', 'Pantaloni della tuta con tasca inclinata e vita elastica', 0, 11);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (494, 14, 325, 'F', 'Pantaloni della tuta e vita elastica e righe', 0, 11);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (495, 13, 325, 'F', 'Pantaloni della tuta monocolore con vita elastica ', 0, 11);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (496, 13, 325, 'F', 'Pantaloni della tuta monocolore con vita elastica ', 0, 11);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (497, 17, 325, 'F', 'Pantaloni dritta con vita alta', 0, 11);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (498, 17, 325, 'F', 'Pantaloni dritta con vita alta', 0, 11);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (499, 17, 325, 'F', 'Pantaloni dritta con vita alta', 0, 11);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (500, 19, 325, 'F', 'Pantaloni in PU ampia con zip ', 0, 11);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (501, 15, 325, 'F', 'Pantaloni larghi stampati con cintura', 0, 11);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (502, 9, 325, 'F', 'Pantaloni monocolore con gamba svasata e vita alta', 0, 11);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (503, 9, 325, 'F', 'Pantaloni monocolore con gamba svasata e vita alta', 0, 11);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (504, 14, 325, 'F', 'Pantaloni plissettati monocolore', 0, 11);
INSERT INTO toj_sitoweb.articolo (ID_articolo, Prezzo, Quantita, Sesso, Descrizione, sconto, ID_categoria) VALUES (505, 15, 325, 'F', 'Pantaloni Tasca Grafico Casual', 0, 11);